name: mila-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx>=4.0.2
  - recommonmark>=0.7.1
  - myst-parser>=0.14.0
  - sphinx-copybutton>=0.3.1
  - sphinx-prompt>=1.4.0
  - sphinx_rtd_theme>=0.5.2
  - pip=22.0
  - pip:
    - sphinx-theme>=1.0
    - sphinx-readable-theme>=1.3
